name: Update nix config

on:
  push:
    branches:
      - main

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          export WORKSPACE="${PWD}"
          nix run .#upgrade-nix-gohip
          git config --global user.name 'autobot'
          git config --global user.email 'gohip.nix@github.com'
          git commit -am "[skip ci] Automated nix hash update"
          git push
