name: Update nix config

on:
  push:
    branches:
      - main

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
                github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          export WORKSPACE="${PWD}"
          nix run .#upgrade-nix-gohip
