name: Go Release

on:
  push:
    tags:
      - 'v*.*.*' # Matches v1.0.0, v2.1.3, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
          RELEASE_VERSION=$(echo ${{ github.ref }} | tr -d 'refs/tags/v')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') # redundant, but just to be sure
        with:
          files: |
            gohip-linux-amd64
            gohip-static-linux-amd64

      - name: Create Debian package
        env:
          DESTDIR: '/tmp/gohip-deb' # keep path absolute - meson has issues with relative paths on CI
        run: |
          mkdir -p $DESTDIR
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} RELEASE_VERSION=$RELEASE_VERSION DESTDIR=$DESTDIR make debian-pkg

      - name: Upload Debian release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            gohip-*-x86_64.deb
            gohip-*-x86_64.deb.md5sum

  centos:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: System dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo make alien
          
          RELEASE_VERSION=$(echo ${{ github.ref }} | tr -d 'refs/tags/v')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: Create CentOS 8 package
        run: |
          wget https://github.com/bechampion/gohip/releases/download/v$RELEASE_VERSION/gohip-$RELEASE_VERSION-x86_64.deb -O gohip-$RELEASE_VERSION-x86_64.deb

          alien -r -k --scripts --target=x86_64 gohip-$RELEASE_VERSION-x86_64.deb
          md5sum gohip-$RELEASE_VERSION-1.x86_64.rpm >> gohip-$RELEASE_VERSION-1.x86_64.rpm

      - name: Upload CentOS 8 release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            gohip-*-1.x86_64.rpm
            gohip-*-1.x86_64.rpm.md5sum

  arch:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare arch package metadata
        run: |
          RELEASE_VERSION=$(echo ${{ github.ref }} | tr -d 'refs/tags/v')
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          
          wget https://github.com/bechampion/gohip/releases/download/v$RELEASE_VERSION/gohip-$RELEASE_VERSION-x86_64.deb -O build-aux/arch/gohip-bin/gohip-$RELEASE_VERSION-x86_64.deb

          MD5_SUM=$(md5sum build-aux/arch/gohip-bin/gohip-$RELEASE_VERSION-x86_64.deb | awk '{print $1}')
          awk -v q="'" -v MD5_SUM=$MD5_SUM -i inplace 'BEGINFILE{print "md5sums=(" q MD5_SUM q ")"}{print}' build-aux/arch/gohip-bin/PKGBUILD
          awk -v RELEASE_VERSION=$RELEASE_VERSION -i inplace 'BEGINFILE{print "pkgver=" q RELEASE_VERSION q ""}{print}' build-aux/arch/gohip-bin/PKGBUILD

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          debug: true
          target: pkgbuild
          pkgname: build-aux/arch/gohip-bin/

      - name: Create arch package checksum file
        run: |
          sudo chown -R $USER .
          md5sum build-aux/arch/gohip-bin/gohip-bin-$RELEASE_VERSION-1-x86_64.pkg.tar.zst >> build-aux/arch/gohip-bin/gohip-bin-$RELEASE_VERSION-1-x86_64.pkg.tar.zst.md5sum

      - name: Upload Arch Linux release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            build-aux/arch/gohip-bin/gohip-bin-*-1-x86_64.pkg.tar.zst
            build-aux/arch/gohip-bin/gohip-bin-*-1-x86_64.pkg.tar.zst.md5sum
